name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm ci
        
    - name: Build Web App
      run: |
        npm run build
        
    - name: Setup Capacitor
      run: |
        npm install -g @capacitor/cli
        
    - name: Sync iOS Platform
      run: |
        npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        
    - name: Install iOS Dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Build iOS App (Debug)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -configuration Debug \
                   -destination generic/platform=iOS \
                   -archivePath $PWD/build/App.xcarchive \
                   archive
                   
    - name: Export iOS App
      run: |
        cd ios/App
        xcodebuild -exportArchive \
                   -archivePath $PWD/build/App.xcarchive \
                   -exportOptionsPlist $PWD/build/ExportOptions.plist \
                   -exportPath $PWD/build/
                   
    - name: Create Export Options
      run: |
        cd ios/App
        mkdir -p build
        cat > build/ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>teamID</key>
            <string></string>
        </dict>
        </plist>
        EOF
        
    - name: Upload iOS Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-${{ github.sha }}
        path: ios/App/build/
        retention-days: 30
        
    - name: Upload iOS Archive
      uses: actions/upload-artifact@v4
      with:
        name: ios-archive-${{ github.sha }}
        path: ios/App/build/App.xcarchive
        retention-days: 30
