name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        npm ci
        
    - name: Build Web App
      run: |
        npm run build
        
    - name: Setup Capacitor
      run: |
        npm install -g @capacitor/cli
        
    - name: Sync iOS Platform
      run: |
        npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        
    - name: Install iOS Dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Configure Code Signing (Development)
      run: |
        cd ios/App
        # Configure automatic signing for development
        sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' App.xcodeproj/project.pbxproj || true
        sed -i '' 's/DEVELOPMENT_TEAM = "";/DEVELOPMENT_TEAM = "";/g' App.xcodeproj/project.pbxproj || true
        sed -i '' 's/CODE_SIGN_IDENTITY = "";/CODE_SIGN_IDENTITY = "iPhone Developer";/g' App.xcodeproj/project.pbxproj || true
                   
    - name: Build iOS App for Simulator (Debug)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -configuration Debug \
                   -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
                   -derivedDataPath build/DerivedData \
                   build
                   
    - name: Build iOS App for Device (Debug - No Signing)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
                   -scheme App \
                   -configuration Debug \
                   -destination generic/platform=iOS \
                   -derivedDataPath build/DerivedData \
                   CODE_SIGNING_ALLOWED=NO \
                   build
                   
    - name: Create Export Options
      run: |
        cd ios/App
        mkdir -p build
        cat > build/ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>compileBitcode</key>
            <false/>
        </dict>
        </plist>
        EOF
        
    - name: Upload iOS Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-${{ github.sha }}
        path: ios/App/build/
        retention-days: 30
        
    - name: Upload iOS Archive
      uses: actions/upload-artifact@v4
      with:
        name: ios-archive-${{ github.sha }}
        path: ios/App/build/App.xcarchive
        retention-days: 30
